name: Automated eBay Scraper

on:
  schedule:
    - cron: '0 */5 * * *'  # Runs every 5 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install selenium pandas webdriver-manager fake-useragent

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push Data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ebay_tech_deals.csv
          git commit -m "Updated eBay deals data [Auto-Scraped]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
